name: Build Executables

on:
  push:
    tags:
      - 'v*'  # 添加标签触发条件，匹配 v1.0.0 这样的标签

jobs:
  # CLI版本构建任务
  build-windows-cli:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
        
    - name: Build EXE
      run: |
        pyinstaller CursorKeepAlive.spec
        
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: CursorPro-CLI-Windows
        path: dist/CursorPro.exe

  # 新增 - Windows GUI版本
  build-windows-gui:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
        pip install PyQt6
        
    - name: Create GUI Spec
      run: |
        python build.py --gui
        
    - name: Build GUI EXE
      run: |
        pyinstaller CursorProGUI.spec
        
    - name: Upload Windows GUI artifact
      uses: actions/upload-artifact@v4
      with:
        name: CursorPro-GUI-Windows
        path: dist/CursorProGUI.exe

  build-macos-arm64-cli:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
        
    - name: Build MacOS ARM executable
      run: |
        pyinstaller CursorKeepAlive.spec
        
    - name: Upload MacOS ARM artifact
      uses: actions/upload-artifact@v4
      with:
        name: CursorPro-CLI-MacOS-ARM64
        path: dist/CursorPro

  # 新增 - macOS ARM64 GUI版本
  build-macos-arm64-gui:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
        pip install PyQt6
        
    - name: Create GUI Spec
      run: |
        python build.py --gui
        
    - name: Build MacOS ARM GUI executable
      run: |
        pyinstaller CursorProGUI.spec
        
    - name: Upload MacOS ARM GUI artifact
      uses: actions/upload-artifact@v4
      with:
        name: CursorPro-GUI-MacOS-ARM64
        path: dist/CursorProGUI.app

  build-linux-cli:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
        
    - name: Build Linux executable
      run: |
        pyinstaller CursorKeepAlive.spec
        
    - name: Upload Linux artifact
      uses: actions/upload-artifact@v4
      with:
        name: CursorPro-CLI-Linux
        path: dist/CursorPro

  # 新增 - Linux GUI版本
  build-linux-gui:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-glx libxkbcommon-x11-0
        pip install PyQt6
        
    - name: Create GUI Spec
      run: |
        python build.py --gui
        
    - name: Build Linux GUI executable
      run: |
        pyinstaller CursorProGUI.spec
        
    - name: Upload Linux GUI artifact
      uses: actions/upload-artifact@v4
      with:
        name: CursorPro-GUI-Linux
        path: dist/CursorProGUI

  build-macos-intel-cli:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        arch -x86_64 pip3 install --upgrade pip
        arch -x86_64 pip3 install pyinstaller
        arch -x86_64 pip3 install -r requirements.txt

    - name: Build MacOS Intel executable
      env:
        TARGET_ARCH: 'x86_64'
      run: |
        arch -x86_64 python3 -m PyInstaller CursorKeepAlive.spec
        
    - name: Upload MacOS Intel artifact
      uses: actions/upload-artifact@v4
      with:
        name: CursorPro-CLI-MacOS-Intel
        path: dist/CursorPro

  # 新增 - macOS Intel GUI版本
  build-macos-intel-gui:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        arch -x86_64 pip3 install --upgrade pip
        arch -x86_64 pip3 install pyinstaller
        arch -x86_64 pip3 install -r requirements.txt
        arch -x86_64 pip3 install PyQt6

    - name: Create GUI Spec
      run: |
        arch -x86_64 python3 build.py --gui
        
    - name: Build MacOS Intel GUI executable
      env:
        TARGET_ARCH: 'x86_64'
      run: |
        arch -x86_64 python3 -m PyInstaller CursorProGUI.spec
        
    - name: Upload MacOS Intel GUI artifact
      uses: actions/upload-artifact@v4
      with:
        name: CursorPro-GUI-MacOS-Intel
        path: dist/CursorProGUI.app

  create-release:
    needs: [
      build-windows-cli, build-windows-gui,
      build-macos-arm64-cli, build-macos-arm64-gui,
      build-linux-cli, build-linux-gui,
      build-macos-intel-cli, build-macos-intel-gui
    ]
    runs-on: ubuntu-22.04
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          
      - name: Create release archives
        run: |
          cd artifacts
          # CLI版本归档
          zip -r CursorPro-CLI-Windows.zip CursorPro-CLI-Windows/
          zip -r CursorPro-CLI-MacOS-ARM64.zip CursorPro-CLI-MacOS-ARM64/
          zip -r CursorPro-CLI-Linux.zip CursorPro-CLI-Linux/
          zip -r CursorPro-CLI-MacOS-Intel.zip CursorPro-CLI-MacOS-Intel/
          # GUI版本归档
          zip -r CursorPro-GUI-Windows.zip CursorPro-GUI-Windows/
          zip -r CursorPro-GUI-MacOS-ARM64.zip CursorPro-GUI-MacOS-ARM64/
          zip -r CursorPro-GUI-Linux.zip CursorPro-GUI-Linux/
          zip -r CursorPro-GUI-MacOS-Intel.zip CursorPro-GUI-MacOS-Intel/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/CursorPro-CLI-Windows.zip
            artifacts/CursorPro-CLI-MacOS-ARM64.zip
            artifacts/CursorPro-CLI-Linux.zip
            artifacts/CursorPro-CLI-MacOS-Intel.zip
            artifacts/CursorPro-GUI-Windows.zip
            artifacts/CursorPro-GUI-MacOS-ARM64.zip
            artifacts/CursorPro-GUI-Linux.zip
            artifacts/CursorPro-GUI-MacOS-Intel.zip

        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
