name: Build Executables

on:
  push:
    tags:
      - 'v*'  # 添加标签触发条件，匹配 v1.0.0 这样的标签

jobs:

  build-macos-intel-cli:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install --no-deps psutil
        pip install -r requirements.txt

    - name: Build MacOS Intel executable
      env:
        ARCHFLAGS: "-arch x86_64"
        MACOS_ARCH: "x86_64"
        TARGET_ARCH: "x86_64"
      run: |
        python build.py
        
    - name: Upload MacOS Intel artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-intel-cli
        path: dist/mac/CursorPro-MacOS-Intel

  # 新增 - macOS Intel GUI版本
  build-macos-intel-gui:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install --no-deps psutil
        pip install -r requirements.txt
        pip install PyQt6
        brew install create-dmg

    - name: Build MacOS Intel GUI executable
      env:
        ARCHFLAGS: "-arch x86_64"
        MACOS_ARCH: "x86_64"
        TARGET_ARCH: "x86_64"
      run: |
        python build.py --gui
        
    - name: Create DMG
      run: |
        create-dmg \
          --volname "CursorPro" \
          --window-pos 200 120 \
          --window-size 800 400 \
          --icon-size 100 \
          --icon "CursorProGUI-MacOS-Intel.app" 200 190 \
          --hide-extension "CursorProGUI-MacOS-Intel.app" \
          --app-drop-link 600 185 \
          "dist/mac/CursorProGUI-MacOS-Intel.dmg" \
          "dist/mac/CursorProGUI-MacOS-Intel.app"
        
    - name: Upload MacOS Intel GUI artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-intel-gui
        path: dist/mac/CursorProGUI-MacOS-Intel.dmg


  create-release:
    needs: [
      # build-windows-cli, build-windows-gui,
      # build-macos-arm64-cli, build-macos-arm64-gui,
      # build-linux-cli, build-linux-gui,
      build-macos-intel-cli, build-macos-intel-gui
    ]
    runs-on: ubuntu-22.04
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/macos-intel-cli/CursorPro-MacOS-Intel
            artifacts/macos-intel-gui/CursorProGUI-MacOS-Intel.dmg
          generate_release_notes: true

        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
